export * from './bad.component'
export * from './cal.component'
export * from './sad.component'
export * from './cad.component'
export * from './mad.component'
export * from './wad.component'
export * from './bad.module'